import { useQueryClient } from "@tanstack/react-query";
import { useNewBooking } from "@/contexts/NewBookingContext";
import { fetchAvailableRooms } from "@/api/bookingAPI";
import type {BookingSession, RequestedRoom} from "@/assets/bookingTypes";
import {createSessionId} from "@/utils/createSessionId";
import {getInitialBookingFormValues} from "@/assets/guestTypes";
import getAdditionalGuestCount from "@/utils/getAdditionalGuestCount";
import {saveBookingSession} from "@/utils/bookingSession";

export function useCreateBookingRequest() {
  const { state, dispatch } = useNewBooking();
  const queryClient = useQueryClient();

  return async (
    checkIn: Date,
    checkOut: Date,
    requestedRooms: RequestedRoom[]
  ) => {
    const sessionId = state.sessionId ?? createSessionId(); // TODO: Will be generated by the backend

    const availableRooms = await queryClient.fetchQuery({
      queryKey: [
        "availability",
        checkIn,
        checkOut,
        requestedRooms,
        sessionId,
      ],
      queryFn: () =>
        fetchAvailableRooms(
          checkIn,
          checkOut,
          requestedRooms,
          sessionId
        ),
    });

    const totalAvailable = Object.values(availableRooms).reduce(
      (sum, room) => sum + room.amount,
      0
    );

    if (totalAvailable < requestedRooms.length) {
      throw new Error("Not enough available rooms");
    }

    const newBookingSession: BookingSession = {
      sessionId: sessionId,
      checkIn: checkIn,
      checkOut: checkOut,
      requestedRooms: requestedRooms,
      guestFormValues: getInitialBookingFormValues(getAdditionalGuestCount(requestedRooms)),
    }

    saveBookingSession(newBookingSession);

    dispatch({
      type: "SET_REQUEST",
      sessionId,
      checkIn,
      checkOut,
      rooms: requestedRooms,
    });
  };
}